# pandas是专⻔为处理表格和混杂数据设计的。

In [1]:
import pandas as pd  
import numpy as np

In [2]:
from pandas import Series, DataFrame    

<font color = blue>pandas的数据结构介绍</font>

<font color = red>Series:⼀种类似于⼀维数组的对象，它由⼀组数据（各种
NumPy数据类型）以及⼀组与之相关的数据标签（即索引）组
成。</font>

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d']

4

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [13]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in  obj2

False

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}

In [20]:
obj3 = Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = Series(sdata, index = states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon          3200.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [35]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

<font color = red>DataFrame:表格型的数据结构，含有一组有序的列，每列可以是不同的值类型</font>

In [36]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Neveda'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop(million)': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [37]:
frame

state  year  pop(million)
0    Ohio  2000           1.5
1    Ohio  2001           1.7
2    Ohio  2002           3.6
3  Nevada  2001           2.4
4  Neveda  2002           2.9

In [38]:
DataFrame(data, columns = ['year', 'state', 'pop(million)']) #指定列顺序

year   state  pop(million)
0  2000    Ohio           1.5
1  2001    Ohio           1.7
2  2002    Ohio           3.6
3  2001  Nevada           2.4
4  2002  Neveda           2.9

In [39]:
frame2 = DataFrame(data, columns = ['year', 'state', 'pop(million)', 'debt'], 
                  index = ['one', 'two', 'three', 'four', 'five'])

In [40]:
frame2

year   state  pop(million) debt
one    2000    Ohio           1.5  NaN
two    2001    Ohio           1.7  NaN
three  2002    Ohio           3.6  NaN
four   2001  Nevada           2.4  NaN
five   2002  Neveda           2.9  NaN

In [41]:
frame2.columns

Index(['year', 'state', 'pop(million)', 'debt'], dtype='object')

In [42]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Neveda
Name: state, dtype: object

In [43]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Neveda
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [45]:
frame2.loc['three']   #  .loc 索引行

year            2002
state           Ohio
pop(million)     3.6
debt             NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop(million)  debt
one    2000    Ohio           1.5  16.5
two    2001    Ohio           1.7  16.5
three  2002    Ohio           3.6  16.5
four   2001  Nevada           2.4  16.5
five   2002  Neveda           2.9  16.5

In [48]:
frame2['debt'] = np.arange(5)
frame2

year   state  pop(million)  debt
one    2000    Ohio           1.5     0
two    2001    Ohio           1.7     1
three  2002    Ohio           3.6     2
four   2001  Nevada           2.4     3
five   2002  Neveda           2.9     4

In [49]:
val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop(million)  debt
one    2000    Ohio           1.5   NaN
two    2001    Ohio           1.7  -1.2
three  2002    Ohio           3.6   NaN
four   2001  Nevada           2.4  -1.5
five   2002  Neveda           2.9  -1.7

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'

In [53]:
frame2

year   state  pop(million)  debt  eastern
one    2000    Ohio           1.5   NaN     True
two    2001    Ohio           1.7  -1.2     True
three  2002    Ohio           3.6   NaN     True
four   2001  Nevada           2.4  -1.5    False
five   2002  Neveda           2.9  -1.7    False

In [54]:
del frame2['eastern']

In [55]:
frame2

year   state  pop(million)  debt
one    2000    Ohio           1.5   NaN
two    2001    Ohio           1.7  -1.2
three  2002    Ohio           3.6   NaN
four   2001  Nevada           2.4  -1.5
five   2002  Neveda           2.9  -1.7

In [56]:
frame2.columns

Index(['year', 'state', 'pop(million)', 'debt'], dtype='object')

<font color = green>嵌套字典传给DataFrame,pandas解释为：外层字典的键作为列，内层键作为行索引</font>

In [57]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [58]:
frame3 = pd.DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [60]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [61]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [63]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [64]:
frame3.index.name = 'year';
frame3.columns.name = 'state'

In [65]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [66]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Neveda', 2.9, -1.7]], dtype=object)

<font color = red>索引对象</font>

In [68]:
obj = Series(range(3), index = ['a', 'b', 'c'])

In [69]:
obj

a    0
b    1
c    2
dtype: int64

In [70]:
index = obj.index

In [71]:
index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [73]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [74]:
index = pd.Index(np.arange(3))

In [75]:
obj2 = Series([1.5, 2.5, 0], index = index)

In [76]:
obj2.index is index

True

In [77]:
obj2

0    1.5
1    2.5
2    0.0
dtype: float64

In [78]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [79]:
'Ohio' in frame3.columns

True

In [80]:
2003 not in frame3.index

True

# 基本功能

# <font size = 2>重新索引</font>

In [81]:
obj = Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [82]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [83]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [84]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [85]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value = 0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [86]:
obj3 = Series(['blue', 'purple', 'yellow'], index = [0, 2 ,4])

In [87]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [88]:
obj3.reindex(range(6), method = 'bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [89]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index = ['a', 'c', 'd'], 
                columns = ['Ohio', 'Texas', 'California'])

In [90]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [91]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [92]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [93]:
states = ['Texas', 'Utah', 'California']

In [94]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

<font color = green size = 2>丢弃指定轴上的项</font>

In [95]:
obj = Series(np.arange(5), index = ['a', 'b', 'c', 'd', 'e'])

In [96]:
new_obj = obj.drop('c')

In [97]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [98]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [99]:
data = DataFrame(np.arange(16).reshape((4, 4)), 
                index = ['Ohio', 'Colorado', 'Utah', 'New York'], 
                columns = ['one', 'two', 'three', 'four'])

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

<font color = green size = 2>索引、选取和过滤</font>

In [104]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c','d'])

In [105]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [106]:
obj['b']

1.0

<font size = 1 color = red>利用标签的切片运算与普通的Python切片运算不同，包含其末端</font>

In [107]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [108]:
obj['b', 'c'] = 5

In [109]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [110]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah','New York'],
                    columns=['one', 'two', 'three','four'])

In [111]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [112]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [113]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [114]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [116]:
data[data < 5] = 0

In [117]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [119]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [121]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [122]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [123]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [124]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [125]:
ser = pd.Series(np.arange(3))

In [126]:
ser

0    0
1    1
2    2
dtype: int32

In [127]:
ser[:1]

0    0
dtype: int32

In [128]:
ser.loc[:1]

0    0
1    1
dtype: int32

In [129]:
ser.iloc[:1]

0    0
dtype: int32

In [130]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c','d', 'e'])

In [131]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [132]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [133]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [134]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [135]:
df1 = DataFrame(np.arange(9).reshape((3, 3)), columns = list('bcd'),
               index = ['Ohio', 'Texas', 'Colorado'])

In [136]:
df2 = DataFrame(np.arange(12).reshape((4, 3)), columns = list('bde'),
               index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [137]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [138]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [139]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [140]:
df1 = DataFrame(np.arange(12).reshape((3, 4)), columns = list('abcd'))

In [141]:
df2 = DataFrame(np.arange(20).reshape((4, 5)), columns = list('abcde'))

In [142]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [143]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [144]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [145]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [146]:
arr = np.arange(12).reshape((3, 4))

In [147]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
arr[0]

array([0, 1, 2, 3])

In [149]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [150]:
frame = DataFrame(np.arange(12).reshape((4, 3)), columns = list('bde'),
                 index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [151]:
series = frame.iloc[0]

In [152]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [153]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [154]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [155]:
series2 = pd.Series(range(3), index = ['b', 'f', 'e'])

In [156]:
frame + series2

b   d     e   f
Utah    0.0 NaN   4.0 NaN
Ohio    3.0 NaN   7.0 NaN
Texas   6.0 NaN  10.0 NaN
Oregon  9.0 NaN  13.0 NaN

In [157]:
series3 = frame['d']

In [158]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [159]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [160]:
frame.sub(series3, axis = 'index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

<font color = red size = 2>函数应用和映射</font>

In [161]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [162]:
frame

b         d         e
Utah    0.975488 -0.977651  0.615507
Ohio    0.251378 -0.901125 -1.071958
Texas  -1.853691 -0.383094 -0.094400
Oregon -0.665697 -0.725539  0.089038

In [163]:
np.abs(frame)

b         d         e
Utah    0.975488  0.977651  0.615507
Ohio    0.251378  0.901125  1.071958
Texas   1.853691  0.383094  0.094400
Oregon  0.665697  0.725539  0.089038

In [164]:
f = lambda x: x.max() - x.min()

In [165]:
frame.apply(f)

b    2.829179
d    0.594556
e    1.687466
dtype: float64

In [166]:
frame.apply(f, axis = 1)

Utah      1.953139
Ohio      1.323336
Texas     1.759291
Oregon    0.814578
dtype: float64

In [167]:
def f(x):
    return Series([x.min(), x.max()], index = ['min', 'max'])

In [168]:
frame.apply(f)

b         d         e
min -1.853691 -0.977651 -1.071958
max  0.975488 -0.383094  0.615507

In [169]:
format = lambda x: '%.2f'  % x

In [170]:
frame.applymap(format)

b      d      e
Utah     0.98  -0.98   0.62
Ohio     0.25  -0.90  -1.07
Texas   -1.85  -0.38  -0.09
Oregon  -0.67  -0.73   0.09

In [171]:
frame['e'].map(format)

Utah       0.62
Ohio      -1.07
Texas     -0.09
Oregon     0.09
Name: e, dtype: object

<font color = red size = 2>排序和命名</font>

In [172]:
obj =  Series(range(4), index = ['d', 'a', 'b', 'c'])

In [173]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [174]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [175]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index = ['three', 'one'],
                 columns = ['d', 'a', 'b', 'c'])

In [176]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [177]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [178]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [179]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [180]:
obj = Series([4, 7, -3, 2])

In [181]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [182]:
obj.sort_index()

0    4
1    7
2   -3
3    2
dtype: int64

In [183]:
obj = Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])

In [184]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [185]:
obj.index.is_unique

False

In [186]:
obj['a']

a    0
a    1
dtype: int64

In [187]:
obj['c']

4

<font color = red size = 2>汇总和计算描述统计</font>

In [188]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                   [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])

In [189]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [190]:
df.sum( )

one    9.25
two   -5.80
dtype: float64

In [191]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [192]:
df.idxmax()

one    b
two    d
dtype: object

In [193]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [194]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [195]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [196]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [197]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

<font color = red size = 2>唯一值、值计数以及成员资格</font>

In [198]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'f', 'e'])

In [199]:
obj.unique()

array(['c', 'a', 'd', 'f', 'e'], dtype=object)

In [200]:
obj.value_counts()

a    3
d    1
f    1
e    1
c    1
dtype: int64

In [201]:
obj.values

array(['c', 'a', 'd', 'a', 'a', 'f', 'e'], dtype=object)

In [204]:
pd.value_counts(obj.values, sort = False)

c    1
e    1
a    3
f    1
d    1
dtype: int64

In [205]:
obj

0    c
1    a
2    d
3    a
4    a
5    f
6    e
dtype: object

In [206]:
mask = obj.isin(['b', 'c'])

In [207]:
mask

0     True
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [208]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [209]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4